import PDFDocument from "pdfkit";

interface ShowSection {
  name: string;
  projectName?: string;
  venue: {
    name: string;
    address?: string;
    contactName?: string;
    contactPhone?: string;
    wifiSsid?: string;
    wifiPassword?: string;
    parking?: string;
    loadIn?: string;
    capacity?: string;
    dressingRooms?: boolean;
    dressingRoomsNotes?: string;
    showers?: boolean;
    showersNotes?: string;
    laundry?: boolean;
    laundryNotes?: string;
    meals?: string;
    mealsNotes?: string;
  } | null;
  scheduleItems: Array<{
    time: string;
    title: string;
    description?: string;
    category?: string;
    location?: string;
    crewNames?: string[];
  }>;
  crew: Array<{
    name: string;
    role?: string;
    phone?: string;
    email?: string;
  }>;
}

interface DailySheetPdfData {
  dateFormatted: string;
  senderName: string;
  showSections: ShowSection[];
  unassignedItems: Array<{
    time: string;
    title: string;
    description?: string;
    category?: string;
    location?: string;
    crewNames?: string[];
  }>;
}

const COLORS = {
  darkBg: "#1e293b",
  white: "#ffffff",
  lightGray: "#f8fafc",
  border: "#e2e8f0",
  lightBorder: "#f1f5f9",
  text: "#1e293b",
  textSecondary: "#64748b",
  textTertiary: "#94a3b8",
  sectionLabel: "#475569",
  link: "#2563eb",
};

function drawRoundedRect(doc: PDFKit.PDFDocument, x: number, y: number, w: number, h: number, r: number, fill: string) {
  doc.save();
  doc.roundedRect(x, y, w, h, r).fill(fill);
  doc.restore();
}

export function generateDailySheetPdf(data: DailySheetPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "LETTER",
      margins: { top: 40, bottom: 40, left: 40, right: 40 },
      bufferPages: true,
      info: {
        Title: `Daily Sheet - ${data.dateFormatted}`,
        Author: data.senderName,
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const leftMargin = doc.page.margins.left;

    doc.fontSize(20).font("Helvetica-Bold").fillColor(COLORS.text);
    doc.text("DAILY SHEET", leftMargin, doc.page.margins.top, { align: "center", width: pageWidth });
    doc.moveDown(0.3);
    doc.fontSize(12).font("Helvetica").fillColor(COLORS.textSecondary);
    doc.text(data.dateFormatted, { align: "center", width: pageWidth });
    doc.moveDown(0.2);
    doc.fontSize(9).fillColor(COLORS.textTertiary);
    doc.text(`Sent by ${data.senderName}`, { align: "center", width: pageWidth });
    doc.moveDown(1.5);

    for (const section of data.showSections) {
      renderShowSection(doc, section, pageWidth, leftMargin);
    }

    if (data.unassignedItems.length > 0) {
      checkPageSpace(doc, 60);
      doc.fontSize(12).font("Helvetica-Bold").fillColor(COLORS.sectionLabel);
      doc.text("GENERAL SCHEDULE", leftMargin, doc.y, { width: pageWidth });
      doc.moveDown(0.5);
      renderScheduleTable(doc, data.unassignedItems, pageWidth, leftMargin);
      doc.moveDown(1);
    }

    doc.moveDown(1);
    const lineY = doc.y;
    doc.moveTo(leftMargin, lineY).lineTo(leftMargin + pageWidth, lineY).strokeColor(COLORS.border).lineWidth(0.5).stroke();
    doc.moveDown(0.5);
    doc.fontSize(8).font("Helvetica").fillColor(COLORS.textTertiary);
    doc.text("Generated by Daily Sheet", { align: "center", width: pageWidth });

    doc.end();
  });
}

function checkPageSpace(doc: PDFKit.PDFDocument, needed: number) {
  const bottomLimit = doc.page.height - doc.page.margins.bottom;
  if (doc.y + needed > bottomLimit) {
    doc.addPage();
  }
}

function renderShowSection(doc: PDFKit.PDFDocument, section: ShowSection, pageWidth: number, leftMargin: number) {
  const venueDetails: string[] = [];
  if (section.venue) {
    if (section.venue.contactName) {
      let ct = `Venue Contact: ${section.venue.contactName}`;
      if (section.venue.contactPhone) ct += ` (${section.venue.contactPhone})`;
      venueDetails.push(ct);
    }
    if (section.venue.wifiSsid) {
      let wf = `WiFi: ${section.venue.wifiSsid}`;
      if (section.venue.wifiPassword) wf += ` / ${section.venue.wifiPassword}`;
      venueDetails.push(wf);
    }
    if (section.venue.parking) venueDetails.push(`Parking: ${section.venue.parking}`);
    if (section.venue.loadIn) venueDetails.push(`Load In: ${section.venue.loadIn}`);
    if (section.venue.capacity) venueDetails.push(`Capacity: ${section.venue.capacity}`);
    if (section.venue.dressingRooms) venueDetails.push(`Dressing Rooms: Yes${section.venue.dressingRoomsNotes ? ` - ${section.venue.dressingRoomsNotes}` : ""}`);
    if (section.venue.showers) venueDetails.push(`Showers: Yes${section.venue.showersNotes ? ` - ${section.venue.showersNotes}` : ""}`);
    if (section.venue.laundry) venueDetails.push(`Laundry: Yes${section.venue.laundryNotes ? ` - ${section.venue.laundryNotes}` : ""}`);
    if (section.venue.meals && section.venue.meals !== "none") {
      const mealsLabel = section.venue.meals === "client_provided" ? "Client Provided" : "Walkaway";
      venueDetails.push(`Meals: ${mealsLabel}${section.venue.mealsNotes ? ` - ${section.venue.mealsNotes}` : ""}`);
    }
  }

  const contentWidth = pageWidth - 24;
  const showTitle = section.projectName
    ? `${section.name.toUpperCase()}  (${section.projectName})`
    : section.name.toUpperCase();

  doc.font("Helvetica-Bold").fontSize(13);
  const titleH = doc.heightOfString(showTitle, { width: contentWidth });
  let totalHeaderH = 10 + titleH + 6;

  let venueTextH = 0;
  if (section.venue) {
    let venueText = section.venue.name;
    if (section.venue.address) venueText += ` — ${section.venue.address}`;
    doc.font("Helvetica").fontSize(9);
    venueTextH = doc.heightOfString(venueText, { width: contentWidth });
    totalHeaderH += venueTextH + 4;

    if (venueDetails.length > 0) {
      doc.font("Helvetica").fontSize(8);
      for (const detail of venueDetails) {
        totalHeaderH += doc.heightOfString(detail, { width: contentWidth }) + 2;
      }
    }
  }
  totalHeaderH += 8;

  checkPageSpace(doc, totalHeaderH + 20);
  const headerY = doc.y;
  drawRoundedRect(doc, leftMargin, headerY, pageWidth, totalHeaderH, 4, COLORS.darkBg);

  doc.fontSize(13).font("Helvetica-Bold").fillColor(COLORS.white);
  doc.text(showTitle, leftMargin + 12, headerY + 10, { width: contentWidth });

  if (section.venue) {
    let venueText = section.venue.name;
    if (section.venue.address) venueText += ` — ${section.venue.address}`;
    doc.fontSize(9).font("Helvetica").fillColor("#d1d5db");
    const venueNameY = headerY + 10 + titleH + 4;
    doc.text(venueText, leftMargin + 12, venueNameY, { width: contentWidth });

    if (venueDetails.length > 0) {
      let detailY = venueNameY + venueTextH + 4;
      doc.fontSize(8).font("Helvetica").fillColor("#9ca3af");
      for (const detail of venueDetails) {
        doc.text(detail, leftMargin + 12, detailY, { width: contentWidth });
        detailY += doc.heightOfString(detail, { width: contentWidth }) + 2;
      }
    }
  }

  doc.y = headerY + totalHeaderH + 8;

  if (section.scheduleItems.length > 0) {
    renderScheduleTable(doc, section.scheduleItems, pageWidth, leftMargin);
  } else {
    doc.fontSize(9).font("Helvetica-Oblique").fillColor(COLORS.textTertiary);
    doc.text("No schedule items for this show.", leftMargin, doc.y, { width: pageWidth });
  }

  doc.moveDown(0.5);

  if (section.crew.length > 0) {
    checkPageSpace(doc, 40);
    doc.fontSize(9).font("Helvetica-Bold").fillColor(COLORS.sectionLabel);
    doc.text("CREW", leftMargin, doc.y, { width: pageWidth });
    doc.moveDown(0.3);
    renderCrewTable(doc, section.crew, pageWidth, leftMargin);
  }

  doc.moveDown(1.2);
}

function renderScheduleTable(doc: PDFKit.PDFDocument, items: ShowSection["scheduleItems"], pageWidth: number, leftMargin: number) {
  const colWidths = {
    time: pageWidth * 0.20,
    item: pageWidth * 0.42,
    category: pageWidth * 0.20,
    location: pageWidth * 0.18,
  };
  const minRowHeight = 20;
  const headerHeight = 20;
  const padding = 6;
  const cellTopPad = 4;

  checkPageSpace(doc, headerHeight + minRowHeight * Math.min(items.length, 3));

  const tableStartY = doc.y;

  doc.rect(leftMargin, tableStartY, pageWidth, headerHeight).fill(COLORS.lightGray);
  doc.moveTo(leftMargin, tableStartY + headerHeight).lineTo(leftMargin + pageWidth, tableStartY + headerHeight).strokeColor(COLORS.border).lineWidth(0.5).stroke();

  doc.fontSize(8).font("Helvetica-Bold").fillColor(COLORS.text);
  let hx = leftMargin + padding;
  doc.text("Time", hx, tableStartY + 5, { width: colWidths.time - padding * 2, lineBreak: false });
  hx += colWidths.time;
  doc.text("Item", hx, tableStartY + 5, { width: colWidths.item - padding * 2, lineBreak: false });
  hx += colWidths.item;
  doc.text("Category", hx, tableStartY + 5, { width: colWidths.category - padding * 2, lineBreak: false });
  hx += colWidths.category;
  doc.text("Location", hx, tableStartY + 5, { width: colWidths.location - padding * 2, lineBreak: false });

  let currentY = tableStartY + headerHeight;

  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    const titleText = item.title || "Untitled";
    const itemColW = colWidths.item - padding * 2;

    doc.font("Helvetica-Bold").fontSize(8);
    let contentHeight = doc.heightOfString(titleText, { width: itemColW });

    if (item.description) {
      doc.font("Helvetica").fontSize(7);
      contentHeight += 2 + doc.heightOfString(item.description, { width: itemColW });
    }
    if (item.crewNames && item.crewNames.length > 0) {
      doc.font("Helvetica").fontSize(7);
      contentHeight += 2 + doc.heightOfString(`Crew: ${item.crewNames.join(", ")}`, { width: itemColW });
    }

    const actualRowHeight = Math.max(minRowHeight, contentHeight + cellTopPad * 2);

    checkPageSpace(doc, actualRowHeight);

    if (i % 2 === 1) {
      doc.rect(leftMargin, currentY, pageWidth, actualRowHeight).fill(COLORS.lightGray);
    }
    doc.moveTo(leftMargin, currentY + actualRowHeight).lineTo(leftMargin + pageWidth, currentY + actualRowHeight).strokeColor(COLORS.lightBorder).lineWidth(0.3).stroke();

    let cx = leftMargin + padding;
    doc.fontSize(8).font("Helvetica").fillColor(COLORS.text);
    doc.text(item.time, cx, currentY + cellTopPad, { width: colWidths.time - padding * 2 });

    cx += colWidths.time;
    doc.font("Helvetica-Bold").fontSize(8).fillColor(COLORS.text);
    doc.text(titleText, cx, currentY + cellTopPad, { width: itemColW });
    let subY = currentY + cellTopPad + doc.heightOfString(titleText, { width: itemColW }) + 2;
    if (item.description) {
      doc.font("Helvetica").fontSize(7).fillColor(COLORS.textSecondary);
      const descH = doc.heightOfString(item.description, { width: itemColW });
      doc.text(item.description, cx, subY, { width: itemColW });
      subY += descH + 2;
    }
    if (item.crewNames && item.crewNames.length > 0) {
      doc.font("Helvetica").fontSize(7).fillColor(COLORS.textSecondary);
      doc.text(`Crew: ${item.crewNames.join(", ")}`, cx, subY, { width: itemColW });
    }

    cx += colWidths.item;
    doc.font("Helvetica").fontSize(8).fillColor(COLORS.text);
    doc.text(item.category || "", cx, currentY + cellTopPad, { width: colWidths.category - padding * 2, ellipsis: true, height: 12, lineBreak: false });

    cx += colWidths.category;
    doc.text(item.location || "", cx, currentY + cellTopPad, { width: colWidths.location - padding * 2, ellipsis: true, height: 12, lineBreak: false });

    currentY += actualRowHeight;
  }

  doc.rect(leftMargin, tableStartY, pageWidth, currentY - tableStartY).strokeColor(COLORS.border).lineWidth(0.5).stroke();

  doc.y = currentY + 4;
}

function renderCrewTable(doc: PDFKit.PDFDocument, crew: ShowSection["crew"], pageWidth: number, leftMargin: number) {
  const colWidths = {
    name: pageWidth * 0.28,
    role: pageWidth * 0.22,
    phone: pageWidth * 0.25,
    email: pageWidth * 0.25,
  };
  const rowHeight = 16;
  const headerHeight = 18;
  const padding = 6;

  checkPageSpace(doc, headerHeight + rowHeight * Math.min(crew.length, 3));

  const tableStartY = doc.y;

  doc.rect(leftMargin, tableStartY, pageWidth, headerHeight).fill(COLORS.lightGray);
  doc.moveTo(leftMargin, tableStartY + headerHeight).lineTo(leftMargin + pageWidth, tableStartY + headerHeight).strokeColor(COLORS.border).lineWidth(0.5).stroke();

  doc.fontSize(7).font("Helvetica-Bold").fillColor(COLORS.text);
  let hx = leftMargin + padding;
  doc.text("Name", hx, tableStartY + 4, { width: colWidths.name - padding * 2 });
  hx += colWidths.name;
  doc.text("Role", hx, tableStartY + 4, { width: colWidths.role - padding * 2 });
  hx += colWidths.role;
  doc.text("Phone", hx, tableStartY + 4, { width: colWidths.phone - padding * 2 });
  hx += colWidths.phone;
  doc.text("Email", hx, tableStartY + 4, { width: colWidths.email - padding * 2 });

  let currentY = tableStartY + headerHeight;

  for (let i = 0; i < crew.length; i++) {
    const c = crew[i];

    checkPageSpace(doc, rowHeight);

    if (i % 2 === 1) {
      doc.rect(leftMargin, currentY, pageWidth, rowHeight).fill(COLORS.lightGray);
    }
    doc.moveTo(leftMargin, currentY + rowHeight).lineTo(leftMargin + pageWidth, currentY + rowHeight).strokeColor(COLORS.lightBorder).lineWidth(0.3).stroke();

    let cx = leftMargin + padding;
    doc.fontSize(7).font("Helvetica").fillColor(COLORS.text);
    doc.text(c.name, cx, currentY + 4, { width: colWidths.name - padding * 2 });
    cx += colWidths.name;
    doc.text(c.role || "", cx, currentY + 4, { width: colWidths.role - padding * 2 });
    cx += colWidths.role;
    doc.fillColor(COLORS.link).text(c.phone || "", cx, currentY + 4, { width: colWidths.phone - padding * 2 });
    cx += colWidths.phone;
    doc.text(c.email || "", cx, currentY + 4, { width: colWidths.email - padding * 2 });

    currentY += rowHeight;
  }

  doc.rect(leftMargin, tableStartY, pageWidth, currentY - tableStartY).strokeColor(COLORS.border).lineWidth(0.5).stroke();

  doc.y = currentY + 4;
}
